### PR TITLE
added rgb and hex

### PR DESCRIPTION
**Pull request by mewzax**
just need to change docs :D

### CODE REVIEW

**Comment by etienne-napoleone** [comment]
hey man!
I didn't spend much time fiddling around with vlang after creating this package.
The package itself is probably crap, I remember that at the time it wasn't even possible to export structs or something like that which led to this catastrophic API design.
I have no time to check this pr/release etc.
You might want to consider forking the repo, I'll be happy to update te readme to redirect to your fork

**Comment by mewzax** [comment]
Yes i also thought the design was weird lol

I forked the repo so if u want u can redirect to the fork, i will update my readme with docs too

**Comment by etienne-napoleone** [comment]
cool merci! will you also publish the package on the vpm (?) registry (?)

**Comment by mewzax** [comment]
I will try. I never submited a package on vpm so i hope they accept forks

**Comment by etienne-napoleone** [comment]
closing this, thanks @Mewzax

**Pull request closed without merging**
